### ISSUE TITLE
config parser problem in script

### ISSUE THREAD

**Issue by RichyMX** [billkenney/qidi_3series_recovery#2]
Hello,

apparently there's a python3 command mismatch happening while attempting to update the firmware through the script you provided, here's what happens:

```
mks@mkspi:~$ /home/mks/max3_probe_recovery.sh
+ cd /home/mks
+ sudo sed -i 's/deb.debian.org\/debian buster-backports/archive.debian.org\/deb                                           ian buster-backports/g' /etc/apt/sources.list
+ sudo mv /home/mks/klipper_config/MKS_THR.cfg /home/mks/klipper_config/MKS_THR.                                           cfg.bak
+ ls /dev/serial/by-id/usb-Klipper_rp2040_05A37A9658994853-if00
+ sed -Ei 's/^/\[mcu MKS_THR\]\nserial:/;s/([0-9][0-9])$/\1\n/' /tmp/path
+ sudo mv /tmp/path /home/mks/klipper_config/MKS_THR.cfg
+ read -p 'do you want to restore the stock klipper_config folder? (y/n): ' kfg
do you want to restore the stock klipper_config folder? (y/n): y
+ [[ y =~ [yY] ]]
+ tar -czf klipper_config.bak.tgz klipper_config
+ rm -rf klipper_config
+ wget --no-check-certificate https://raw.githubusercontent.com/billkenney/qidi_                                           3series_recovery/main/klipper_config.tgz
--2024-12-22 12:14:25--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/klipper_config.tgz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.1                                           33, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9313 (9.1K) [application/octet-stream]
Saving to: ‘klipper_config.tgz’

klipper_config.tgz  100%[===================>]   9.09K  --.-KB/s    in 0.002s

2024-12-22 12:14:25 (5.66 MB/s) - ‘klipper_config.tgz’ saved [9313/9313]

+ tar -xzf klipper_config.tgz
+ rm klipper_config.tgz
+ wget --no-check-certificate https://raw.githubusercontent.com/billkenney/qidi_                                           3series_recovery/main/printer-max3_probe.cfg
--2024-12-22 12:14:25--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/printer-max3_probe.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.1                                           33, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24460 (24K) [text/plain]
Saving to: ‘printer-max3_probe.cfg’

printer-max3_probe. 100%[===================>]  23.89K  --.-KB/s    in 0.006s

2024-12-22 12:14:25 (3.63 MB/s) - ‘printer-max3_probe.cfg’ saved [24460/24460]

+ mv printer-max3_probe.cfg /home/mks/klipper_config/printer.cfg
+ echo 'your old klipper_config folder has been backed up to klipper_config.bak.                                           tgz and the stock klipper_config folder and printer.cfg have been installed'
your old klipper_config folder has been backed up to klipper_config.bak.tgz and                                            the stock klipper_config folder and printer.cfg have been installed
+ wget --no-check-certificate https://raw.githubusercontent.com/billkenney/qidi_                                           3series_recovery/main/mksclient-max3.deb
--2024-12-22 12:14:25--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/mksclient-max3.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.1                                           33, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6210784 (5.9M) [application/octet-stream]
Saving to: ‘mksclient-max3.deb.3’

mksclient-max3.deb. 100%[===================>]   5.92M  9.16MB/s    in 0.6s

2024-12-22 12:14:26 (9.16 MB/s) - ‘mksclient-max3.deb.3’ saved [6210784/6210784]

+ sudo dpkg -i mksclient-max3.deb
(Reading database ... 147535 files and directories currently installed.)
Preparing to unpack mksclient-max3.deb ...
**Unpacking makerbase-client (0.1.1) over (0.1.1) ...
Setting up makerbase-client (0.1.1) ...
Traceback (most recent call last):
  File "/root/merge.py", line 3, in <module>
ModuleNotFoundError: No module named 'ConfigParser'**
+ rm mksclient-max3.deb
rm: remove write-protected regular file 'mksclient-max3.deb'? y
+ read -p 'do you want to update your screen firmware (unnecessary if its alread                                           y on the latest firmware, this update takes like 30 min)? (y/n): ' sfmw
do you want to update your screen firmware (unnecessary if its already on the la                                           test firmware, this update takes like 30 min)? (y/n): n
+ [[ n =~ [yY] ]]
+ sudo chown -R mks:mks /home/mks/klipper /home/mks/klipper_config /home/mks/kli                                           pper_config.bak.tgz /home/mks/klipper_logs /home/mks/klippy-env /home/mks/moonra                                           ker /home/mks/moonraker-env /home/mks/fluidd
+ echo 'the printer firmware updates have been installed. turn your printer off,                                            wait for 15 seconds, and turn it back on. if you'\''ve chosen to install the sc                                           reen firmware, there should be a white screen with a progress indicator. it coul                                           d take a few minutes for the update to begin, so don'\''t be impatient. once tha                                           t'\''s complete, reboot your printer again and you should be good to go'
the printer firmware updates have been installed. turn your printer off, wait fo                                           r 15 seconds, and turn it back on. if you've chosen to install the screen firmwa                                           re, there should be a white screen with a progress indicator. it could take a fe                                           w minutes for the update to begin, so don't be impatient. once that's complete,                                            reboot your printer again and you should be good to go
mks@mkspi:~$ cd ~ ; wget --no-check-certificate https://raw.githubusercontent.co                                           m/billkenney/qidi_3series_recovery/main/max3_bltouch_recovery.sh ; chmod +x max3                                           _bltouch_recovery.sh ; ./max3_bltouch_recovery.sh
--2024-12-22 12:15:48--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/max3_bltouch_recovery.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.1                                           33, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2540 (2.5K) [text/plain]
Saving to: ‘max3_bltouch_recovery.sh.1’

max3_bltouch_recove 100%[===================>]   2.48K  --.-KB/s    in 0s

2024-12-22 12:15:48 (8.27 MB/s) - ‘max3_bltouch_recovery.sh.1’ saved [2540/2540]

do you want to restore the stock klipper_config folder? (y/n): y
--2024-12-22 12:15:50--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/klipper_config.tgz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.1                                           33, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9313 (9.1K) [application/octet-stream]
Saving to: ‘klipper_config.tgz’

klipper_config.tgz  100%[===================>]   9.09K  --.-KB/s    in 0.001s

2024-12-22 12:15:51 (11.2 MB/s) - ‘klipper_config.tgz’ saved [9313/9313]

--2024-12-22 12:15:51--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/printer-max3_bltouch.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.1                                           33, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24628 (24K) [text/plain]
Saving to: ‘printer-max3_bltouch.cfg’

printer-max3_bltouc 100%[===================>]  24.05K  --.-KB/s    in 0.008s

2024-12-22 12:15:51 (3.08 MB/s) - ‘printer-max3_bltouch.cfg’ saved [24628/24628]

your old klipper_config folder has been backed up to klipper_config.bak.tgz and                                            the stock klipper_config folder and printer.cfg have been installed
--2024-12-22 12:15:51--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/mksclient-max3.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.1                                           33, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6210784 (5.9M) [application/octet-stream]
Saving to: ‘mksclient-max3.deb’

  mksclient-max3.deb  100%[===================>]   5.92M  9.15MB/s    in 0.6s
  
  2024-12-22 12:15:52 (9.15 MB/s) - ‘mksclient-max3.deb’ saved [6210784/6210784]
  
  (Reading database ... 147535 files and directories currently installed.)
  Preparing to unpack mksclient-max3.deb ...
  Unpacking makerbase-client (0.1.1) over (0.1.1) ...
  Setting up makerbase-client (0.1.1) ...
  Traceback (most recent call last):
    File "/root/merge.py", line 3, in <module>
  ModuleNotFoundError: No module named 'ConfigParser'
  do you want to update your screen firmware (unnecessary if its already on the la                                           test firmware, this update takes like 30 min)? (y/n): y
  --2024-12-22 12:16:15--  https://raw.githubusercontent.com/billkenney/qidi_3seri                                           es_recovery/main/800_480.tft
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.1                                           33, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.                                           133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21596308 (21M) [application/octet-stream]
Saving to: ‘800_480.tft’

800_480.tft         100%[===================>]  20.60M  10.5MB/s    in 2.0s

2024-12-22 12:16:18 (10.5 MB/s) - ‘800_480.tft’ saved [21596308/21596308]

the printer firmware updates have been installed. turn your printer off, wait fo                                           r 15 seconds, and turn it back on. if you've chosen to install the screen firmware, there should be a white screen with a progress indicator. it could take a fe                                           w minutes for the update to begin, so don't be impatient. once that's complete,                                            reboot your printer again and you should be good to go
```

**Comment by billkenney** [comment]
Does the printer work after installing the firmware? Typically you can ignore errors during install..
